"""empty message

Revision ID: 3fa9be15f77b
Revises: 38c4e85512a9
Create Date: 2019-03-25 17:24:16.750524

"""

# revision identifiers, used by Alembic.
revision = '3fa9be15f77b'
down_revision = '38c4e85512a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
