"""empty message

Revision ID: d1b80ff90e34
Revises: 3fa9be15f77b
Create Date: 2019-03-26 16:28:57.115694

"""

# revision identifiers, used by Alembic.
revision = 'd1b80ff90e34'
down_revision = '3fa9be15f77b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
