"""empty message

Revision ID: e9e70a0e9df1
Revises: d1b80ff90e34
Create Date: 2019-03-27 16:26:26.819716

"""

# revision identifiers, used by Alembic.
revision = 'e9e70a0e9df1'
down_revision = 'd1b80ff90e34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
